export const DISPATCH = {
  Abyssal: 'abyssal',
  Alchemical: 'alchemical',
  'Dragon-Blooded': 'dragon-blooded',
  'Dragon King': 'dragon-king',
  // Ghost: 'ghost',
  // 'God-Blooded': 'god-blooded',
  Infernal: 'infernal',
  Jadeborn: 'jadeborn',
  Lunar: 'lunar',
  Mortal: 'mortal',
  Raksha: 'raksha',
  Sidereal: 'sidereal',
  Solar: 'solar',
};
